### ISSUE TITLE
CI Failed with ARFoundation 4.2 (unityci/editor:2021.3.1f1-ios-1.0.1)

### ISSUE THREAD

**Issue by ketourneau** [game-ci/docker#173]
**Bug description**

Pipeline failes to build (same commit works with unityci/editor:2020.3.33f1-ios-1.0.1).

**How to reproduce**

Launch a pipeline with Unity 2021.3.1f1 (or 2021.3.0f1) and with ARFoundation 4.2.2.

```
Library/PackageCache/com.unity.xr.arkit@4.2.2/Editor/ARKitReferenceImageLibraryBuildProcessor.cs(140,35): error CS0246: The type or namespace name 'PBXProject' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.unity.xr.arkit@4.2.2/Editor/ARKitReferenceImageLibraryBuildProcessor.cs(141,38): error CS0103: The name 'PBXProject' does not exist in the current context
Library/PackageCache/com.unity.xr.arkit@4.2.2/Editor/ARKitReferenceImageLibraryBuildProcessor.cs(142,40): error CS0103: The name 'File' does not exist in the current context
Library/PackageCache/com.unity.xr.arkit@4.2.2/Editor/ARKitReferenceImageLibraryBuildProcessor.cs(162,30): error CS1061: 'XcodeAssetCatalog' does not contain a definition for 'WriteAndAddToPBXProject' and no accessible extension method 'WriteAndAddToPBXProject' accepting a first argument of type 'XcodeAssetCatalog' could be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.unity.xr.arkit@4.2.2/Editor/ARKitReferenceImageLibraryBuildProcessor.cs(165,17): error CS0103: The name 'File' does not exist in the current context
Assets/Packages/Unity.XR.Mock/Editor/PlaneAttacher.cs(45,17): warning CS0618: 'ARAnchorManager.RemoveAnchor(ARAnchor)' is obsolete: 'Call Destroy() on the ARAnchor component to remove it. (2020-10-06)'
Assets/Packages/Unity.XR.Mock/Editor/SimulateAnchors.cs(34,30): warning CS0618: 'ARAnchorManager.AddAnchor(Pose)' is obsolete: 'Add an anchor using AddComponent<ARAnchor>(). (2020-10-06)'
Assets/Tests/Scripts/ModelTest.cs(322,28): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
AssetDatabase: script compilation time: 61.686197s
Scripts have compiler errors.
```

**Comment by ketourneau** [comment]
Same error with 2021.3.2f1 and ARFoundation 4.2.3

**Comment by ketourneau** [comment]
Same error with 2021.3.4f1 and with ARFoundation 5.0.0-pre.12 or ARFoundation 4.23

Has anyone managed to build Unity 2021.3.X and ARFoundation with Game-ci ?

**Comment by adozzer** [comment]
> Same error with 2021.3.4f1 and with ARFoundation 5.0.0-pre.12 or ARFoundation 4.23
> 
> Has anyone managed to build Unity 2021.3.X and ARFoundation with Game-ci ?

I had to use an older 4.1.7 ARFoundation. It buids successfuly with 2021.3.5f1

**Comment by ketourneau** [comment]
It work now with 2021.3.10f1 and with ARFoundation 5.X
